services:
  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - keycloak-db
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: https://id.mdegenaro.com
      KC_HOSTNAME_STRICT: "true"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8080
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_DEBUG: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    command:
      - start
    ports:
      - "8085:8080"
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-proxy
      traefik.http.routers.keycloak.rule: Host(`id.mdegenaro.com`)
      traefik.http.routers.keycloak.entrypoints: websecure
      traefik.http.routers.keycloak.tls.certresolver: letsencrypt
      traefik.http.services.keycloak.loadbalancer.server.port: 8080
    networks:
      - keycloak-net
      - traefik-proxy

volumes:
  keycloak-db-data:
    external: true
    name: keycloak_keycloak-db-data

networks:
  keycloak-net:
    driver: bridge
  traefik-proxy:
    external: true
