services:
  home-assistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: home-assistant
    restart: unless-stopped
    environment:
        TZ: "America/New_York"
        PUID: "99"
        PGID: "100"
        UMASK: "022"
    ports:
      - "8123:8123"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes: 
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/cache/tmp/piper:/media
    devices:
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230830190144-if00:/dev/ttyACM0
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-proxy
      traefik.http.routers.homeassistant.rule: Host(`home.mdegenaro.com`)
      traefik.http.routers.homeassistant.entrypoints: websecure
      traefik.http.routers.homeassistant.tls.certresolver: letsencrypt
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
    networks:
      - ha-net
      - traefik-proxy
      - br0:
        ipv4_address: 192.168.1.166

networks:
  ha-net:
    external: true
  traefik-proxy:
    external: true
  br0:
    external: true
