services:
  home-assistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: home-assistant
    restart: unless-stopped
    environment:
        TZ: "America/New_York"
        PUID: "99"
        PGID: "100"
        UMASK : "022"
    ports:
      - "8123:8123"
    volumes: 
      - /mnt/user/appdata/homeassistant:/config
      - /mnt/cache/tmp/piper:/media
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6e4730db3386ec11ab665d1719c2d21c-if00

networks:
  ha-net:
    external: true
