services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    restart: unless-stopped
    environment:
      PUID: "99"
      PGID: "100"
      TZ: "America/New_York"
      WHISPER_MODEL: "tiny-int8"
      WHISPER_BEAM: "1"
      WHISPER_LANG: "en"
    ports:
      - "10300:10300"
    volumes:
      - /mnt/user/appdata/faster-whisper:/config
    networks:
      - ha-net

networks:
  ha-net:
    external: true

