services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      TZ: "America/New_York"
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-proxy
      traefik.http.routers.vaultwarden.rule: Host(`passwords.dege.app`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.tls.certresolver: letsencrypt
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
    ports:
      - "4743:80"
    volumes:
      - "/mnt/user/appdata/vaultwarden:/data"
    networks:
      - ha-net
      - traefik-proxy

networks:
  ha-net:
    external: true
  traefik-proxy:
    external: true
