services:
  speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    container_name: speaches
    restart: unless-stopped
    environment:
      TZ: "America/New_York"
      _UNSTABLE_VAD_FILTER: "False"
    ports:
      - "8333:8000"
    volumes:
      - /mnt/user/appdata/speaches/cache:/home/ubuntu/.cache/huggingface/hub
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
    #           driver: "nvidia"
    #           device_ids: ["0"]
    networks:
      - ha-net

networks:
  ha-net:
    external: true
